algorithms:
  covertree:
    candidate_limits_enabled: false
    metric: l2
    type: CoverTree
  covertree_v2:
    metric: l2
    type: CoverTreeV2
  exact:
    indexer:
      metric: l2
      type: BruteForceIndexer
    metric: l2
    searcher:
      metric: l2
      type: LinearSearcher
    type: Composite
  faiss_lsh:
    indexer:
      metric: l2
      num_bits: 256
      type: FaissLSHIndexer
    metric: l2
    searcher:
      metric: l2
      nprobe: 10
      type: FaissSearcher
    type: Composite
  hnsw:
    indexer:
      M: 16
      efConstruction: 200
      efSearch: 100
      metric: l2
      type: HNSWIndexer
    metric: l2
    searcher:
      metric: l2
      nprobe: 10
      type: FaissSearcher
    type: Composite
  ivf_flat:
    indexer:
      index_type: IVF100,Flat
      metric: l2
      nprobe: 10
      type: FaissIVFIndexer
    metric: l2
    searcher:
      metric: l2
      nprobe: 10
      type: FaissSearcher
    type: Composite
  ivf_pq:
    indexer:
      index_key: IVF256,PQ64
      metric: l2
      nprobe: 24
      type: FaissFactoryIndexer
    metric: l2
    searcher:
      metric: l2
      nprobe: 24
      type: FaissSearcher
    type: Composite
  ivf_sq8:
    indexer:
      index_key: IVF256,SQ8
      metric: l2
      nprobe: 24
      type: FaissFactoryIndexer
    metric: l2
    searcher:
      metric: l2
      nprobe: 24
      type: FaissSearcher
    type: Composite
  pq:
    indexer:
      index_key: PQ64
      metric: l2
      type: FaissFactoryIndexer
    metric: l2
    searcher:
      metric: l2
      nprobe: 24
      type: FaissSearcher
    type: Composite
data_dir: /storage/ice-shared/cs8903onl/vectordb-retrieval/datasets
dataset: random
dataset_options:
  dimensions: 64
  ground_truth_k: 200
  seed: 7
  test_size: 512
  train_size: 20000
force_download: false
metric: l2
n_queries: 256
output_prefix: random_20251204_091614
query_batch_size: 128
repeat: 2
seed: 42
topk: 20
